# See more config options
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
auto_detect_remappings = true
broadcast = 'contracts/broadcast'
cache_path = 'contracts/cache'
libs = ['contracts/libs']
out = 'contracts/out'
remappings = [
    '@forge-std/=contracts/libs/forge-std/src/',
    '@openzeppelin/=contracts/libs/openzeppelin-contracts/',
    'openzeppelin/=contracts/libs/openzeppelin-contracts/',
    '@risc0-ethereum/=contracts/libs/risc0-ethereum/contracts/src/',
    'risc0-ethereum/=contracts/libs/risc0-ethereum/contracts/src/',
]
solc = '0.8.33'
script = 'contracts/scripts'
src = 'contracts/src'
test = 'contracts/test'