name: On PRs

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Go Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.10.1
          args: --timeout=3m --config=./.golangci.yaml

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Run Go Unit Tests
        run: make go-test

  sol-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge Version
        run: forge --version

      - name: Run Sol Lint
        run: make sol-lint

  sol-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Sol Unit Tests
        run: make sol-test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Run Integration Test
        run: make test-integration
